apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lovegress
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - list
      - watch
