apiVersion: apps/v1
kind: Deployment
metadata:
  name: lovegress
  namespace: lovegress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lovegress
  template:
    metadata:
      labels:
        app: lovegress
    spec:
      containers:
        - name: lovegress
          image: lovegress:latest
          imagePullPolicy: Never # making minikube work
          terminationMessagePolicy: FallbackToLogsOnError
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
