apiVersion: v1
kind: Service
metadata:
  name: lovegress
  namespace: lovegress
spec:
  type: LoadBalancer
  selector:
    app: lovegress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
